---
- hosts: hostname
  tasks:
    - name: Install Samba Service
      apt:
          name: samba
          state: latest
      when:
         - ansible_distribution == "Ubuntu"
         - ansible_distribution_major_version == "16"
         
    - name: Start Samba Service
      service:
          name: "{{ item }}"
          state: started
      with_items:
          - 'smb'
          - 'nmb'
    - name: Install Samba Service
      yum:
          name: samba
          state: latest
      when:
         - ansible_distribution == "CentOs"
         - ansible_distribution_major_version == "7"
          
...
