---
- hosts: hostname
  tasks:
  become: yes
  remote_user: root
    - name: Install Samba Service
      apt:
          name: samba
          state: latest
      when:
         - ansible_distribution == "Ubuntu"
         - ansible_distribution_major_version == "16"

    - name: Install Samba Service
        yum:
          name: samba
          state: latest
      when:
         - ansible_distribution == "CentOs"
         - ansible_distribution_major_version == "7"
          
...
